@startuml backup-export

b2 -> "tapu-backups": /instance/create-token
note right: creates a token and a temporary ftp user

"tapu-backups" --> b2: token and ftp credentials

b2 -> "tapu-backups": ftp connect

b2 -[#blue]> "tapu-backups": <font color="blue">export backup</font>

b2 -> "tapu-backups": ftp close

b2 -> "tapu-backups": /instance/release-token
note right: deletes token and temporary ftp user

"tapu-backups" --> b2: "token_released"

@enduml